runtimes:
  configs:
    java:
      image: "java-runner:1.2"
      compile-command:
        - bash
        - -c
        - javac -cp /usr/local/dep/myapp.jar /app/*.java
      run-command:
        - bash
        - -c
        - java -cp /app:/usr/local/dep/myapp.jar Program

    python:
      image: "python-runner:1.0"
      run-command:
        - python3
        - /app/Program.py


