runtimes:
  configs:
    java:
      image: "java-runner:1.2"
      compile-command:
        - javac
        - -cp
        - /app/dep/myapp.jar
        - -d
        - /app/exec
        - /app/exec/Program.java
      run-command:
        - java
        - -cp
        - /app/dep/myapp.jar:/app/exec
        - Program

    python:
      image: "python-runner:1.0"
      run-command:
        - python3
        - /app/Program.py


